/**
 * Patches window.fetch to proxy mempool.space and okx.com requests through
 * our Express backend, avoiding CORS issues. Follows the same pattern as
 * the onesat reference implementation.
 *
 * Only mempool.space/holdings and okx.com need proxying — other APIs
 * (Binance, CoinGecko, CoinPaprika, Kraken) have CORS headers and
 * work directly from the browser.
 *
 * The SDK generates malformed mempool URLs (missing slashes between path
 * segments like "apiaddress" instead of "api/address"). This patch fixes
 * those before proxying.
 */

import { API_URL } from "@/lib/constants";

let patched = false;

/**
 * Fix malformed mempool.space URLs generated by the Atomiq SDK.
 * Examples:
 *   /testnet4/apiaddress/<addr>/utxo  → /testnet4/api/address/<addr>/utxo
 *   /testnet4/apiv1/fees/recommended  → /testnet4/api/v1/fees/recommended
 *   /testnet4/apiv1/cpfp/<txid>       → /testnet4/api/v1/cpfp/<txid>
 *   /testnet4/apitx                   → /testnet4/api/tx
 */
function fixMempoolPath(path: string): string {
  path = path.replace(/\/api(address|tx|block|blocks|mining|fees|v1|lightning)/g, "/api/$1");
  return path;
}

export function patchFetchForAtomiq(): void {
  if (typeof window === "undefined" || patched) return;
  patched = true;

  const originalFetch = window.fetch.bind(window);

  window.fetch = function (
    input: RequestInfo | URL,
    init?: RequestInit
  ): Promise<Response> {
    let url: string;
    if (typeof input === "string") {
      url = input;
    } else if (input instanceof URL) {
      url = input.href;
    } else if (input instanceof Request) {
      url = input.url;
      if (!init) {
        init = {
          method: input.method,
          headers: input.headers,
          body: input.body,
        };
      }
    } else {
      url = String(input);
    }

    // Proxy mempool.space and mempool.holdings through our Express backend
    if (url.includes("mempool.space") || url.includes("mempool.holdings")) {
      let proxied = url.replace(/https?:\/\/mempool\.(space|holdings)/, `${API_URL}/proxy/mempool`);
      proxied = fixMempoolPath(proxied);
      return originalFetch(proxied, init);
    }

    // All other APIs (OKX, Binance, CoinGecko, CoinPaprika, Kraken,
    // intermediary nodes) are called directly — no proxy needed.
    return originalFetch(input, init);
  };
}
